### ISSUE TITLE
Bug in SSD1306 scrolling (with fix)

### ISSUE THREAD

**Issue by adenton0** [Arcachofo/SimulIDE-dev#16]
https://github.com/Arcachofo/SimulIDE-dev/blame/74e5996741c599992146caa3b85643025b63d2b2/src/components/outputs/displays/ssd1306.cpp#L181

When scrolling, pixels are messed up on one side when scrolling RIGHT.  Problem is ssd1306.cpp lines 181 + 182:
<code>
       &#09;if( c < 127  ) m_aDispRam[c][row] = m_aDispRam[c-1][row];
       &#09;if( col == 0 ) m_aDispRam[0][row] = end;
</code>
Both lines have incorrect tests in the if().  CHANGE BOTH AS FOLLOWS:
<code>
       &#09;if( c > 0  ) m_aDispRam[c][row] = m_aDispRam[c-1][row];
       &#09;if( c == 0 ) m_aDispRam[0][row] = end;&#09;&#09;&#09;// or just use *else*
</code>
i.e.
L181: test should be c>0 not <127
L182: test should use 'c' not 'col' (and could entirely be replaced with 'else')

Adam.

**Comment by Arcachofo** [comment]
Thank you.
Solved at 1a360a3.
